# Server
spring.application.name=product-service
server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=ecommerce-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
# 600000ms = 10 phút — product cache tự expire sau 10 phút
