spring.application.name=gateway
server.port=8080

# Auth Service Route
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Product Service Route
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=http://product-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**,/api/categories/**

# JWT
jwt.secret=ecommerce-secret-key-must-be-at-least-256-bits-long-for-hs256